---

- hosts: all
  become: true
  pre_tasks:

  - name: install updates (alma linux)
    dnf:
      update_only: yes 
      update_cache: yes
    when: ansible_distribution == "AlmaLinux"


- hosts: web_servers
  become: true
  tasks:

  - name: install apache and php packages for alma linux
    dnf:
      name:
       - httpd
       - php
      state: latest
    when: ansible_distribution == "AlmaLinux"

- hosts: file_servers
  become: true
  tasks:

  - name: install mariadb package for alma linux
    dnf:
      name:
       - mariadb
      state: latest
    when: ansible_distribution == "AlmaLinux"
